import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";
import tanstack from "ultracite/oxlint/tanstack";

export default defineConfig({
  extends: [core, react, tanstack],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    ".agents/skills/**",
    ".pnpmfile.cjs",
    "postcss.config.cjs",
    "src/db/schema/auth-schema.ts",
    "src/routeTree.gen.ts",
    "vitest/tanstack-entry-stub.ts",
    "worker-configuration.d.ts",
  ],
  overrides: [
    {
      files: ["src/routes/**/*.ts", "src/routes/**/*.tsx"],
      rules: {
        "func-style": "off",
        "no-use-before-define": "off",
        "react/function-component-definition": "off",
        "require-await": "off",
        "unicorn/no-await-expression-member": "off",
      },
    },
    {
      files: [
        "**/*.stories.ts",
        "**/*.stories.tsx",
        "src/stories/**/*.ts",
        "src/stories/**/*.tsx",
        "src/storybook/**/*.ts",
        "src/storybook/**/*.tsx",
      ],
      rules: {
        "func-style": "off",
        "no-await-in-loop": "off",
        "no-bitwise": "off",
        "no-empty-function": "off",
        "no-eq-null": "off",
        "no-nested-ternary": "off",
        "no-promise-executor-return": "off",
        "no-use-before-define": "off",
        "prefer-named-capture-group": "off",
        "promise/avoid-new": "off",
        "react/function-component-definition": "off",
        "require-await": "off",
        "require-unicode-regexp": "off",
        "typescript/array-type": "off",
        "typescript/await-thenable": "off",
        "typescript/no-confusing-void-expression": "off",
        "typescript/no-floating-promises": "off",
        "typescript/no-non-null-assertion": "off",
        "typescript/no-unnecessary-type-conversion": "off",
        "typescript/no-unsafe-type-assertion": "off",
        "typescript/prefer-nullish-coalescing": "off",
        "typescript/promise-function-async": "off",
        "typescript/strict-void-return": "off",
        "unicorn/filename-case": "off",
        "unicorn/import-style": "off",
      },
    },
    {
      files: [
        "**/*.test.ts",
        "**/*.test.tsx",
        "**/*.spec.ts",
        "**/*.spec.tsx",
        "**/test-helpers.ts",
        "**/__mocks__/**/*.ts",
        "src/test/**/*.ts",
        "src/test/**/*.tsx",
        "scripts/**/*.ts",
      ],
      rules: {
        "func-style": "off",
        "no-await-in-loop": "off",
        "no-promise-executor-return": "off",
        "no-use-before-define": "off",
        "no-useless-return": "off",
        "promise/avoid-new": "off",
        "require-await": "off",
        "require-unicode-regexp": "off",
        "sort-keys": "off",
        "typescript/await-thenable": "off",
        "typescript/consistent-type-imports": "off",
        "typescript/no-base-to-string": "off",
        "typescript/no-explicit-any": "off",
        "typescript/no-unsafe-argument": "off",
        "typescript/no-unsafe-assignment": "off",
        "typescript/no-unsafe-call": "off",
        "typescript/no-unsafe-member-access": "off",
        "typescript/no-unsafe-return": "off",
        "typescript/no-unsafe-type-assertion": "off",
        "typescript/strict-void-return": "off",
        "unicorn/import-style": "off",
        "unicorn/no-immediate-mutation": "off",
      },
    },
    {
      files: ["src/features/bookmarks/server/fetch-page-title.server.ts"],
      rules: {
        complexity: "off",
        eqeqeq: "off",
        "no-await-in-loop": "off",
        "no-bitwise": "off",
        "no-eq-null": "off",
        "no-use-before-define": "off",
        "prefer-named-capture-group": "off",
        "require-unicode-regexp": "off",
        "typescript/no-unsafe-argument": "off",
        "typescript/no-unsafe-assignment": "off",
        "typescript/no-unsafe-call": "off",
        "typescript/no-unsafe-member-access": "off",
        "typescript/no-unsafe-type-assertion": "off",
        "unicorn/no-lonely-if": "off",
      },
    },
  ],
  rules: {
    complexity: "off",
    "default-case": "off",
    eqeqeq: "off",
    "import/first": "off",
    "no-empty-function": "off",
    "no-eq-null": "off",
    "no-use-before-define": "off",
    "prefer-destructuring": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/prefer-await-to-then": "off",
    "react-hooks/rules-of-hooks": "off",
    "react/exhaustive-effect-dependencies": "off",
    "react/hooks": "off",
    "react/refs": "off",
    "react/set-state-in-effect": "off",
    "react/todo": "off",
    "require-await": "off",
    "require-unicode-regexp": "off",
    "sort-keys": "off",
    "typescript/consistent-return": "off",
    "typescript/no-deprecated": "off",
    "typescript/no-misused-promises": "off",
    "typescript/no-non-null-assertion": "off",
    "typescript/no-unsafe-argument": "off",
    "typescript/no-unsafe-assignment": "off",
    "typescript/no-unsafe-call": "off",
    "typescript/no-unsafe-member-access": "off",
    "typescript/no-unsafe-return": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/only-throw-error": "off",
    "typescript/strict-boolean-expressions": "off",
    "typescript/strict-void-return": "off",
    "unicorn/no-await-expression-member": "off",
  },
});
