allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true

catalog:
  react-scan: 0.5.7

catalogMode: strict

catalogs:
  authentication:
    '@better-auth/drizzle-adapter': 1.7.1
    better-auth: 1.7.1
  build:
    '@cloudflare/vite-plugin': 1.53.1
    '@vitejs/plugin-react': 6.1.0
    'vite': 8.2.2
  database:
    '@libsql/client': 0.17.4
    '@tursodatabase/database': 0.7.2
    drizzle-orm: 1.0.0-rc.5-169397b
    drizzle-kit: 1.0.0-rc.5-ab785fc
    drizzle-seed: 1.0.0-rc.5-ab785fc
  debug:
    '@tanstack/devtools-vite': 0.8.5
    '@tanstack/react-devtools': 0.10.12
    '@tanstack/react-query-devtools': 5.101.4
    '@tanstack/react-router-devtools': 1.167.1
  envvars:
    '@dotenvx/dotenvx': 1.75.1
    '@t3-oss/env-core': 0.13.11
  errors:
    '@praha/error-factory': 1.4.1
    'react-error-boundary': 6.1.3
  form:
    '@conform-to/react': 1.21.1
    '@conform-to/valibot': 1.21.1
  format:
    oxfmt: 0.64.0
  framework:
    '@tanstack/react-query': 5.101.4
    '@tanstack/react-router': 1.170.31
    '@tanstack/react-router-ssr-query': 1.167.1
    '@tanstack/react-start': 1.168.48
  githooks:
    lefthook: 2.1.10
  lint:
    '@markuplint/jsx-parser': 4.18.3
    '@markuplint/react-spec': 4.18.0
    knip: 6.32.2
    markuplint: 4.18.3
    oxlint: 1.79.0
    oxlint-tsgolint: 0.25.0
  react:
    '@types/react': 19.2.17
    '@types/react-dom': 19.2.3
    react: 19.2.8
    react-dom: 19.2.8
  runtime:
    '@types/node': 25.9.5
    wrangler: 4.125.0
  script:
    tsx: 4.23.12
  test:
    '@cloudflare/vitest-pool-workers': 0.22.0
    vitest: 4.1.11
  typescript:
    '@tsconfig/strictest': 2.0.8
    typescript: 7.0.2
  storybook:
    '@storybook/addon-docs': 10.5.10
    '@storybook/builder-vite': 10.5.10
    '@storybook/tanstack-react': 10.5.10
    storybook-device-viewports: 0.1.2
    storybook: 10.5.10
  ui:
    '@fontsource/noto-sans-jp': 5.3.0
    '@pandacss/dev': 1.12.0
    lucide-react: 1.33.0
    postcss: 8.5.26
    react-aria-components: 1.20.0
  uuid:
    uuidv7: 1.2.1
  validation:
    valibot: 1.4.2
  rpc:
    '@orpc/client': 1.15.0
    '@orpc/server': 1.15.0
    '@orpc/tanstack-query': 1.15.0

engineStrict: true

minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.16'
  - '@better-auth/drizzle-adapter@1.6.16'
  - '@better-auth/kysely-adapter@1.6.16'
  - '@better-auth/memory-adapter@1.6.16'
  - '@better-auth/mongo-adapter@1.6.16'
  - '@better-auth/prisma-adapter@1.6.16'
  - '@better-auth/telemetry@1.6.16'
  - better-auth@1.6.16

overrides:
  '@babel/core>semver': 7.8.0
  '@babel/helper-compilation-targets>semver': 7.8.0
  '@tanstack/query-core': 5.100.11
  chokidar: 5.0.0
  kysely: 0.28.17
  esbuild: 0.28.1

saveExact: true

strictDepBuilds: true

trustPolicy: no-downgrade
