allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true

catalogMode: strict

catalogs:
  authentication:
    '@better-auth/drizzle-adapter': 1.6.23
    better-auth: 1.6.23
  build:
    '@cloudflare/vite-plugin': 1.45.1
    '@vitejs/plugin-react': 6.0.3
    chokidar: 5.0.0
    'vite': 8.1.5
  database:
    '@libsql/client': 0.17.4
    '@tursodatabase/database': 0.7.0
    drizzle-orm: 1.0.0-rc.4
    drizzle-kit: 1.0.0-rc.4
    drizzle-seed: 1.0.0-rc.4
  debug:
    '@tanstack/devtools-vite': 0.8.1
    '@tanstack/react-devtools': 0.10.8
    '@tanstack/react-query-devtools': 5.101.4
    '@tanstack/react-router-devtools': 1.167.0
  envvars:
    '@dotenvx/dotenvx': 1.75.1
    '@t3-oss/env-core': 0.13.11
  errors:
    '@praha/error-factory': 1.4.1
    'react-error-boundary': 6.1.2
  form:
    '@formisch/react': 0.8.0
  format:
    oxfmt: 0.59.0
  framework:
    '@tanstack/react-query': 5.101.4
    '@tanstack/react-router': 1.170.18
    '@tanstack/react-router-ssr-query': 1.167.1
    '@tanstack/react-start': 1.168.32
    '@tanstack/router-plugin': 1.168.23
  githooks:
    lefthook: 2.1.10
  lint:
    oxlint: 1.74.0
    oxlint-tsgolint: 0.25.0
  react:
    '@types/react': 19.2.17
    '@types/react-dom': 19.2.3
    react: 19.2.7
    react-dom: 19.2.7
  runtime:
    '@types/node': 25.9.5
    wrangler: 4.112.0
  script:
    tsx: 4.23.1
  test:
    '@cloudflare/vitest-pool-workers': 0.18.6
    vitest: 4.1.10
  typescript:
    '@tsconfig/strictest': 2.0.8
    '@typescript/native-preview': 7.0.0-dev.20260707.2
    typescript: 6.0.3
  typespec:
    '@typespec/compiler': 1.14.0
    '@typespec/http': 1.14.0
    '@typespec/openapi': 1.14.0
    '@typespec/openapi3': 1.14.0
    '@typespec/rest': 0.84.0
  ui:
    '@base-ui/react': 1.6.0
    '@pandacss/dev': 1.11.4
    lucide-react: 1.25.0
    postcss: 8.5.21
  uuid:
    uuidv7: 1.2.1
  validation:
    valibot: 1.4.2

engineStrict: true

minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.16'
  - '@better-auth/drizzle-adapter@1.6.16'
  - '@better-auth/kysely-adapter@1.6.16'
  - '@better-auth/memory-adapter@1.6.16'
  - '@better-auth/mongo-adapter@1.6.16'
  - '@better-auth/prisma-adapter@1.6.16'
  - '@better-auth/telemetry@1.6.16'
  - better-auth@1.6.16

overrides:
  '@babel/core>semver': 7.8.0
  '@babel/helper-compilation-targets>semver': 7.8.0
  '@tanstack/query-core': 5.100.11
  chokidar: 'catalog:build'
  kysely: 0.28.17
  esbuild: 0.28.1

saveExact: true

strictDepBuilds: true

trustPolicy: no-downgrade
