import { exec } from "node:child_process";
import { createHash } from "node:crypto";
import { access, symlink, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { promisify } from "node:util";

const ENV_FILES = [".env", ".env.development"] as const;
const LOCAL_ENV_FILE = ".env.development.local";

const PORT_RANGE_START = 9100;
const PORT_RANGE_SIZE = 800;

const EXIT_FAILURE = 1;

const execAsync = promisify(exec);

const isGitWorktree = async (): Promise<boolean> => {
  const [gitDir, commonDir] = await Promise.all([
    execAsync("git rev-parse --git-dir", { encoding: "utf-8" }).then((r) =>
      r.stdout.trim()
    ),
    execAsync("git rev-parse --git-common-dir", { encoding: "utf-8" }).then(
      (r) => r.stdout.trim()
    ),
  ]);
  return gitDir !== commonDir;
};

const exists = async (filePath: string): Promise<boolean> => {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
};

const worktreeHash = (worktreeRoot: string): string =>
  createHash("sha256").update(worktreeRoot).digest("hex");

const localEnvContent = (worktreeRoot: string): string => {
  const hash = worktreeHash(worktreeRoot);
  const port =
    PORT_RANGE_START +
    (Number.parseInt(hash.slice(0, 8), 16) % PORT_RANGE_SIZE);
  const project = `pantry-${hash.slice(0, 8)}`;

  return [
    "# Generated by scripts/symlink-env-for-worktree.ts.",
    "# Overrides the shared .env.development so this git worktree can run its own",
    "# libSQL container on a unique host port (see compose.yaml).",
    `TURSO_PROJECT=${project}`,
    `TURSO_PORT=${port}`,
    `TURSO_CONNECTION_URL=http://127.0.0.1:${port}`,
    "",
  ].join("\n");
};

const symlinkSharedEnvFiles = async (mainRepoRoot: string): Promise<void> => {
  for (const file of ENV_FILES) {
    const source = resolve(mainRepoRoot, file);
    const target = resolve(process.cwd(), file);

    if (!(await exists(source))) {
      console.warn(`Source ${source} not found. Skipping ${file}.`);
      continue;
    }

    if (await exists(target)) {
      console.log(`${file} already exists. Skipping.`);
      continue;
    }

    await symlink(source, target);
    console.log(`Symlinked ${target} -> ${source}`);
  }
};

const writeLocalEnvFile = async (): Promise<void> => {
  const target = resolve(process.cwd(), LOCAL_ENV_FILE);

  if (await exists(target)) {
    console.log(`${LOCAL_ENV_FILE} already exists. Skipping.`);
    return;
  }

  await writeFile(target, localEnvContent(process.cwd()), "utf-8");
  console.log(`Wrote per-worktree libSQL settings to ${LOCAL_ENV_FILE}`);
};

const main = async (): Promise<void> => {
  if (!(await isGitWorktree())) {
    console.log("Not a git worktree. Skipping.");
    return;
  }

  const commonDir = (
    await execAsync("git rev-parse --git-common-dir", { encoding: "utf-8" })
  ).stdout.trim();
  const mainRepoRoot = resolve(commonDir, "..");

  await symlinkSharedEnvFiles(mainRepoRoot);
  await writeLocalEnvFile();
};

try {
  await main();
} catch (error) {
  console.error("Failed to prepare env files:", error);
  process.exit(EXIT_FAILURE);
}
