/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as ProtectedBookmarksIndexRouteImport } from './routes/_protected/bookmarks/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedTagsIndexRouteImport } from './routes/_protected/tags/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ProtectedBookmarksIdIndexRouteImport } from './routes/_protected/bookmarks/$id/index'
import { Route as ProtectedBookmarksIdEditRouteImport } from './routes/_protected/bookmarks/$id/edit'
import { Route as ProtectedBookmarksNewIndexRouteImport } from './routes/_protected/bookmarks/new/index'
import { Route as ProtectedBookmarksQuickIndexRouteImport } from './routes/_protected/bookmarks/quick/index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBookmarksIndexRoute = ProtectedBookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTagsIndexRoute = ProtectedTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBookmarksIdIndexRoute =
  ProtectedBookmarksIdIndexRouteImport.update({
    id: '/bookmarks/$id/',
    path: '/bookmarks/$id/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedBookmarksIdEditRoute =
  ProtectedBookmarksIdEditRouteImport.update({
    id: '/bookmarks/$id/edit',
    path: '/bookmarks/$id/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedBookmarksNewIndexRoute =
  ProtectedBookmarksNewIndexRouteImport.update({
    id: '/bookmarks/new/',
    path: '/bookmarks/new/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedBookmarksQuickIndexRoute =
  ProtectedBookmarksQuickIndexRouteImport.update({
    id: '/bookmarks/quick/',
    path: '/bookmarks/quick/',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/bookmarks/': typeof ProtectedBookmarksIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/tags/': typeof ProtectedTagsIndexRoute
  '/bookmarks/$id/edit': typeof ProtectedBookmarksIdEditRoute
  '/bookmarks/$id/': typeof ProtectedBookmarksIdIndexRoute
  '/bookmarks/new/': typeof ProtectedBookmarksNewIndexRoute
  '/bookmarks/quick/': typeof ProtectedBookmarksQuickIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/bookmarks': typeof ProtectedBookmarksIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/tags': typeof ProtectedTagsIndexRoute
  '/bookmarks/$id/edit': typeof ProtectedBookmarksIdEditRoute
  '/bookmarks/$id': typeof ProtectedBookmarksIdIndexRoute
  '/bookmarks/new': typeof ProtectedBookmarksNewIndexRoute
  '/bookmarks/quick': typeof ProtectedBookmarksQuickIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_protected/bookmarks/': typeof ProtectedBookmarksIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/tags/': typeof ProtectedTagsIndexRoute
  '/_protected/bookmarks/$id/edit': typeof ProtectedBookmarksIdEditRoute
  '/_protected/bookmarks/$id/': typeof ProtectedBookmarksIdIndexRoute
  '/_protected/bookmarks/new/': typeof ProtectedBookmarksNewIndexRoute
  '/_protected/bookmarks/quick/': typeof ProtectedBookmarksQuickIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/bookmarks/'
    | '/settings/'
    | '/tags/'
    | '/bookmarks/$id/edit'
    | '/bookmarks/$id/'
    | '/bookmarks/new/'
    | '/bookmarks/quick/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/bookmarks'
    | '/settings'
    | '/tags'
    | '/bookmarks/$id/edit'
    | '/bookmarks/$id'
    | '/bookmarks/new'
    | '/bookmarks/quick'
  id:
    | '__root__'
    | '/_protected'
    | '/_protected/'
    | '/sign-in/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_protected/bookmarks/'
    | '/_protected/settings/'
    | '/_protected/tags/'
    | '/_protected/bookmarks/$id/edit'
    | '/_protected/bookmarks/$id/'
    | '/_protected/bookmarks/new/'
    | '/_protected/bookmarks/quick/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SignInIndexRoute: typeof SignInIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/bookmarks/': {
      id: '/_protected/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof ProtectedBookmarksIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tags/': {
      id: '/_protected/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof ProtectedTagsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/bookmarks/$id/': {
      id: '/_protected/bookmarks/$id/'
      path: '/bookmarks/$id'
      fullPath: '/bookmarks/$id/'
      preLoaderRoute: typeof ProtectedBookmarksIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/bookmarks/$id/edit': {
      id: '/_protected/bookmarks/$id/edit'
      path: '/bookmarks/$id/edit'
      fullPath: '/bookmarks/$id/edit'
      preLoaderRoute: typeof ProtectedBookmarksIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/bookmarks/new/': {
      id: '/_protected/bookmarks/new/'
      path: '/bookmarks/new'
      fullPath: '/bookmarks/new/'
      preLoaderRoute: typeof ProtectedBookmarksNewIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/bookmarks/quick/': {
      id: '/_protected/bookmarks/quick/'
      path: '/bookmarks/quick'
      fullPath: '/bookmarks/quick/'
      preLoaderRoute: typeof ProtectedBookmarksQuickIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedBookmarksIndexRoute: typeof ProtectedBookmarksIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedTagsIndexRoute: typeof ProtectedTagsIndexRoute
  ProtectedBookmarksIdEditRoute: typeof ProtectedBookmarksIdEditRoute
  ProtectedBookmarksIdIndexRoute: typeof ProtectedBookmarksIdIndexRoute
  ProtectedBookmarksNewIndexRoute: typeof ProtectedBookmarksNewIndexRoute
  ProtectedBookmarksQuickIndexRoute: typeof ProtectedBookmarksQuickIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedBookmarksIndexRoute: ProtectedBookmarksIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedTagsIndexRoute: ProtectedTagsIndexRoute,
  ProtectedBookmarksIdEditRoute: ProtectedBookmarksIdEditRoute,
  ProtectedBookmarksIdIndexRoute: ProtectedBookmarksIdIndexRoute,
  ProtectedBookmarksNewIndexRoute: ProtectedBookmarksNewIndexRoute,
  ProtectedBookmarksQuickIndexRoute: ProtectedBookmarksQuickIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  SignInIndexRoute: SignInIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
