/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedTagsIndexRouteImport } from './routes/_protected/tags/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedBookmarksIndexRouteImport } from './routes/_protected/bookmarks/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedBookmarksNewRouteImport } from './routes/_protected/bookmarks/new'
import { Route as ProtectedBookmarksIdRouteImport } from './routes/_protected/bookmarks/$id'
import { Route as ProtectedBookmarksIdEditRouteImport } from './routes/_protected/bookmarks/$id.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTagsIndexRoute = ProtectedTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBookmarksIndexRoute = ProtectedBookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBookmarksNewRoute = ProtectedBookmarksNewRouteImport.update({
  id: '/bookmarks/new',
  path: '/bookmarks/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBookmarksIdRoute = ProtectedBookmarksIdRouteImport.update({
  id: '/bookmarks/$id',
  path: '/bookmarks/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBookmarksIdEditRoute =
  ProtectedBookmarksIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedBookmarksIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/sign-up': typeof SignUpRoute
  '/sign-in/': typeof SignInIndexRoute
  '/bookmarks/$id': typeof ProtectedBookmarksIdRouteWithChildren
  '/bookmarks/new': typeof ProtectedBookmarksNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bookmarks/': typeof ProtectedBookmarksIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/tags/': typeof ProtectedTagsIndexRoute
  '/bookmarks/$id/edit': typeof ProtectedBookmarksIdEditRoute
}
export interface FileRoutesByTo {
  '/sign-up': typeof SignUpRoute
  '/': typeof ProtectedIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/bookmarks/$id': typeof ProtectedBookmarksIdRouteWithChildren
  '/bookmarks/new': typeof ProtectedBookmarksNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bookmarks': typeof ProtectedBookmarksIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/tags': typeof ProtectedTagsIndexRoute
  '/bookmarks/$id/edit': typeof ProtectedBookmarksIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/_protected/bookmarks/$id': typeof ProtectedBookmarksIdRouteWithChildren
  '/_protected/bookmarks/new': typeof ProtectedBookmarksNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/bookmarks/': typeof ProtectedBookmarksIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/tags/': typeof ProtectedTagsIndexRoute
  '/_protected/bookmarks/$id/edit': typeof ProtectedBookmarksIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-up'
    | '/sign-in/'
    | '/bookmarks/$id'
    | '/bookmarks/new'
    | '/api/auth/$'
    | '/bookmarks/'
    | '/settings/'
    | '/tags/'
    | '/bookmarks/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-up'
    | '/'
    | '/sign-in'
    | '/bookmarks/$id'
    | '/bookmarks/new'
    | '/api/auth/$'
    | '/bookmarks'
    | '/settings'
    | '/tags'
    | '/bookmarks/$id/edit'
  id:
    | '__root__'
    | '/_protected'
    | '/sign-up'
    | '/_protected/'
    | '/sign-in/'
    | '/_protected/bookmarks/$id'
    | '/_protected/bookmarks/new'
    | '/api/auth/$'
    | '/_protected/bookmarks/'
    | '/_protected/settings/'
    | '/_protected/tags/'
    | '/_protected/bookmarks/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SignUpRoute: typeof SignUpRoute
  SignInIndexRoute: typeof SignInIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tags/': {
      id: '/_protected/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof ProtectedTagsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/bookmarks/': {
      id: '/_protected/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof ProtectedBookmarksIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/bookmarks/new': {
      id: '/_protected/bookmarks/new'
      path: '/bookmarks/new'
      fullPath: '/bookmarks/new'
      preLoaderRoute: typeof ProtectedBookmarksNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/bookmarks/$id': {
      id: '/_protected/bookmarks/$id'
      path: '/bookmarks/$id'
      fullPath: '/bookmarks/$id'
      preLoaderRoute: typeof ProtectedBookmarksIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/bookmarks/$id/edit': {
      id: '/_protected/bookmarks/$id/edit'
      path: '/edit'
      fullPath: '/bookmarks/$id/edit'
      preLoaderRoute: typeof ProtectedBookmarksIdEditRouteImport
      parentRoute: typeof ProtectedBookmarksIdRoute
    }
  }
}

interface ProtectedBookmarksIdRouteChildren {
  ProtectedBookmarksIdEditRoute: typeof ProtectedBookmarksIdEditRoute
}

const ProtectedBookmarksIdRouteChildren: ProtectedBookmarksIdRouteChildren = {
  ProtectedBookmarksIdEditRoute: ProtectedBookmarksIdEditRoute,
}

const ProtectedBookmarksIdRouteWithChildren =
  ProtectedBookmarksIdRoute._addFileChildren(ProtectedBookmarksIdRouteChildren)

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedBookmarksIdRoute: typeof ProtectedBookmarksIdRouteWithChildren
  ProtectedBookmarksNewRoute: typeof ProtectedBookmarksNewRoute
  ProtectedBookmarksIndexRoute: typeof ProtectedBookmarksIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedTagsIndexRoute: typeof ProtectedTagsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedBookmarksIdRoute: ProtectedBookmarksIdRouteWithChildren,
  ProtectedBookmarksNewRoute: ProtectedBookmarksNewRoute,
  ProtectedBookmarksIndexRoute: ProtectedBookmarksIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedTagsIndexRoute: ProtectedTagsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  SignUpRoute: SignUpRoute,
  SignInIndexRoute: SignInIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
