name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Lint with Oxlint
        shell: bash
        run: |
          pnpm oxlint . --format=github

  markuplint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Lint markup with markuplint
        shell: bash
        run: |
          pnpm markuplint "**/*.{tsx,jsx}" --format=github

  format-check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Format check with Oxfmt
        shell: bash
        run: |
          pnpm run format:check

  typecheck:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Typecheck
        shell: bash
        run: |
          pnpm run typecheck

  knip:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Knip
        shell: bash
        run: |
          pnpm run knip --reporter github-actions

  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Build
        shell: bash
        run: |
          pnpm run build

  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Test
        shell: bash
        run: |
          pnpm run test
