name: Production Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: production-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Cloudflare Pages production
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Build
        shell: bash
        run: |
          pnpm run build

      - name: Deploy production
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >-
            pages deploy ./dist
            --project-name pantry
            --branch=main
